// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA16df8alXpzlZDhaQIXrx-o3A0g0bIYfs',
    appId: '1:925921555588:web:f5ba1c4c5b4f27fbeb7ed1',
    messagingSenderId: '925921555588',
    projectId: 'mymusics-b0d22',
    authDomain: 'mymusics-b0d22.firebaseapp.com',
    storageBucket: 'mymusics-b0d22.firebasestorage.app',
    measurementId: 'G-8PF7TSQMMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGz-0AKYRmew81uf3KncxIGiVwGplSLa8',
    appId: '1:925921555588:android:436948672be993c5eb7ed1',
    messagingSenderId: '925921555588',
    projectId: 'mymusics-b0d22',
    storageBucket: 'mymusics-b0d22.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw-6roCsWDED_U9k_ilViFCIPuk9lT0RM',
    appId: '1:925921555588:ios:a4274c87ae847451eb7ed1',
    messagingSenderId: '925921555588',
    projectId: 'mymusics-b0d22',
    storageBucket: 'mymusics-b0d22.firebasestorage.app',
    iosBundleId: 'com.example.myMusics',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw-6roCsWDED_U9k_ilViFCIPuk9lT0RM',
    appId: '1:925921555588:ios:a4274c87ae847451eb7ed1',
    messagingSenderId: '925921555588',
    projectId: 'mymusics-b0d22',
    storageBucket: 'mymusics-b0d22.firebasestorage.app',
    iosBundleId: 'com.example.myMusics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA16df8alXpzlZDhaQIXrx-o3A0g0bIYfs',
    appId: '1:925921555588:web:4a77492527387187eb7ed1',
    messagingSenderId: '925921555588',
    projectId: 'mymusics-b0d22',
    authDomain: 'mymusics-b0d22.firebaseapp.com',
    storageBucket: 'mymusics-b0d22.firebasestorage.app',
    measurementId: 'G-MWRQM1QKC3',
  );
}
